services:
  elasticsearch:
    container_name: elasticsearch
    environment:
    - discovery.type=single-node
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    ports:
    - 9200:9200
    restart: unless-stopped
  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.0-rc.1
    ports:
    - 19530:19530
    - 9091:9091
    restart: unless-stopped
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
    - 6333:6333
    restart: unless-stopped
  redis:
    container_name: redis-vec
    image: redis/redis-stack-server:latest
    ports:
    - 6380:6379
    restart: unless-stopped
  weaviate:
    container_name: weaviate
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: none
      ENABLE_MODULES: none
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      QUERY_DEFAULTS_LIMIT: 25
    image: semitechnologies/weaviate:latest
    ports:
    - 8080:8080
    restart: unless-stopped
version: '3.8'
